FIRST	STL		RETADR		SAVE RETURN ADDRESS
FIRST	STL		RETADR		SAVE RETURN ADDRESS
COPY    START   1000		COPY FILE FROM INPUT TO OUTPUT

CLOOP   JSUB 	RDREC		READ INPUT RECORD
COPY    START   1000		COPY FILE FROM INPUT TO OUTPUT

	    LDA		LENGTH		TEST FOR EOF (LENGTH = 0)
	    COMP	ZERO
	    JEQ	 	ENDFIL		EXIT IF EOF FOUND

	    JSUB	WRREC		WRITE OUTPUT RECORD
	    J 		CLOOP		LOOP
ENDFIL  	EOF			INSERT END OF FILE MARKER
ENDFIL  	EOF			INSERT END OF FILE MARKER
ENDFIL  	EOF			INSERT END OF FILE MARKER
	    STA
	   		SET LENGTH = 3
	    STA		LENGTH
	    JSUB	WRREC		WRITE EOF
	    LDL		0RETADR		GET RETURN ADDRESS
	    RSUB             	RETURN TO CALLER

POF   	BYTE	'EFFFFFFFFFFFFFFFF
POF   	BYTE	EFFFFFFFFFFFFFFFF'
POF   	BYTE	'EFFFFFFFFFFFFFFFF'
POF   	BYTE	EFFFFFFFFFFFFFFFF
EOF   	BYTE	C'EFFFFFFFFFFFFFFFF
THREE  	WORD	3f
ZERO   	WORD
RsdfsdfsdfE1ADR  RESWPPPPPPPPPppppppp 	1
LENGTH  RESW 				LENGTH OF RECORD
BUFFER 	RESB 	4096		4096-BYTE BUFFER AREA

.
.	SUBROUTINE TO READ RECORD INTO BUFFER
.
RDREC   LDX		ZERO		CLEAR LOOP COUNTER
	    LDA		ZERO		CLEAR A TO ZERO
RLOOP  	TD 		INPUT		TEST INPUT DEVICE
	    JEQ		RLOOP		LOOP UNTIL READY
	    RD		INPUT		READ CHARACTER INTO REGISTAR A
	    COMP    ZERO		TEST FOR END OF RECORD (X'00')
	    JEQ		EXIT		EXIT LOOP IF EOF
	    STCH	X'sd'fsdf' BUFFER,X	STORE CHARCTER IN BUFFER
	    TIX		MAXLEN		LOOP UNLESS MAX LENGTH
	    JLT		RLOOP	  	HAS BEEN REACHED
EXIT   	STX		LENGTH		SAVE RECORD LENGTH
	    RSUB              	RETURN TO CALLER
INPUT  	BYTE	X'Fsdf'''1' TEK CODE FOR INPUT DEVICE
MAXLEN 	WORD	4096

.
.	SUBROUTINE TO WRITE RECORD FROM BUFFER
.
WRREC  	LDX		ZERO		CLEAR LOOP COUNTER
WLOOP	TD		OUTPUT		TEST OUTPUT DEVICE
	   	JEQ 	WLOOP		LOOP UNTIL READY
	    LDCH	BUFFER,	GET CHARCTER FROM BUFFER
	    WD		OUTPUT		WRITE CHARACTER
	   	TIX		LENGTH		LOOP UNTIL ALL CHARACTERS
	    JLT		WLOOP	  	HAVE BEEN WRITTEN
	    RSUB                RETURN TO CALLER
OUTPUT  BYTE	X'0500000000000000000000000000000000000000000000000000000000000000000000'		CODE FOR OUTPUT DEVICE
